HRWebApp/HRWebAppUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRWebApp.BLL;
using HRWebApp.Models;

namespace HRWebAppUI.Controllers
{
    public class AdminController : Controller
    {
        [HttpGet]
        public ActionResult Jobs()
        {
            var manager = new JobManager();
            var model = manager.GetAllJobs();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddJob()
        {
            return View(new Job());
        }

        [HttpPost]
        public ActionResult AddJob(Job job)
        {
            var manager = new JobManager();
            manager.AddJob(job);
            return RedirectToAction("Jobs");
        }

        [HttpGet]
        public ActionResult EditJob(int id)
        {
            var manager = new JobManager();
            var model = manager.GetJob(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditJob(Job job)
        {
            var manager = new JobManager();
            manager.EditJob(job);
            return RedirectToAction("Jobs");
        }

        [HttpGet]
        public ActionResult DeleteJob(int id)
        {
            var manager = new JobManager();
            var model = manager.GetJob(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult DeleteJob(Job job)
        {
            var manager = new JobManager();
            manager.DeleteJob(job);
            return RedirectToAction("Jobs");
        }

        [HttpGet]
        public ActionResult Applications()
        {
            var manager = new ApplicationManager();
            var model = manager.GetAllApplications();
            return View(model.ToList());
        } 

        [HttpGet]
        public ActionResult SingleApplication(int id)
        {
            var manager = new ApplicationManager();
            var application = manager.GetApplication(id);
            return View(application);
        }
    }
}

HRWebApp/HRWebAppUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRWebAppUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HRWebApp/HRWebAppUI/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRWebApp.BLL;
using HRWebApp.Models;

namespace HRWebAppUI.Controllers
{
    public class JobController : Controller
    {
        [HttpGet]
        public ActionResult Jobs()
        {
            var manager = new JobManager();
            var model = manager.GetAllJobs();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddApplication(int id)
        {
            var application = new Application();
            var jobManager = new JobManager();
            application.JobApplyingFor = jobManager.GetJob(id);
            return View(application);
        }

        [HttpPost]
        public ActionResult AddApplication(Application application)
        {
            var manager = new ApplicationManager();            
            if (ModelState.IsValid)
            {
                manager.AddApplication(application);
                return RedirectToAction("Jobs");
            }           
            return AddApplication(application.ApplicationId);
        }
    }
}

HRWebApp/HRWebAppUI/Views/Admin/AddJob.cshtml
@model HRWebApp.Models.Job

@{
    ViewBag.Title = "AddJob";
}

<h2>AddJob</h2>

<div class="row">
    <div class="col-xs-12">
        <h4>Add A Job</h4>
        @Html.ActionLink("Return To List", "Jobs", "Admin")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                @Html.LabelFor(m => m.JobTitle)
                @Html.TextBoxFor(m => m.JobTitle, new {@class = "form-control", placeholder = "Job Title"})
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.JobDescription)
                @Html.TextAreaFor(m => m.JobDescription, new {@class = "form-control", placeholder = "Job Title"})
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.JobRequirement)
                @Html.TextAreaFor(m => m.JobRequirement, new { @class = "form-control", placeholder = "Job Title" })
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Save</button>
        }
    </div>
</div>

HRWebApp/HRWebAppUI/Views/Admin/Applications.cshtml
@model List<HRWebApp.Models.Application>

@{
    ViewBag.Title = "Applications";
}

<div class="row">
    <div class="col-xs-12">
        <h3>All Applications: </h3>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <table class="table">
            <thead>
            <tr>
                <th>Application ID</th>
                <th>Applicant Name</th>
                <th>State</th>
                <th>Skill Set</th>
                <th>Job</th>
                <th></th>
            </tr>
            </thead>
            @foreach (var application in Model)
            {
                <tr>
                    <td>
                        @application.ApplicationId
                    </td>
                    <td>
                        @application.Name
                    </td>
                    <td>
                        @application.Address.State
                    </td>
                    <td>
                        @application.SkillSet
                    </td>
                    <td>
                        @application.JobApplyingFor.JobTitle
                    </td>
                    <td>
                        @Html.ActionLink("See Full Application","SingleApplication","Admin", new {id = application.ApplicationId}, new {@class="btn btn-info"})
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

HRWebApp/HRWebAppUI/Views/Admin/DeleteJob.cshtml
@model HRWebApp.Models.Job

@{
    ViewBag.Title = "DeleteJob";
}


<h3>Are you sure you want to delete this job?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobRequirement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobRequirement)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.HiddenFor(m => m.JobId)
        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Cancel", "Jobs","Admin", null, new {@class = "btn btn-info"})
        </div>
    }
</div>

HRWebApp/HRWebAppUI/Views/Admin/EditJob.cshtml
@model HRWebApp.Models.Job

@{
    ViewBag.Title = "EditJob";
}

<div style="width: 70%">
    @using (Html.BeginForm())
    {


        <div class="form-horizontal">
            <h4>Edit Job</h4>
            @Html.ActionLink("Back to List", "Jobs", "Admin")
            <hr />

            <div class="form-group">
                @Html.LabelFor(model => model.JobTitle, new { @class = "control-label col-md-2" })
                <div class="col-lg-10">
                    @Html.TextBoxFor(model => model.JobTitle, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.JobDescription, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.JobDescription, new { @class = "form-control", rows = 7 })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.JobRequirement, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.JobRequirement, new { @class = "form-control", rows = 7 })
                </div>
            </div>

            @Html.HiddenFor(model => model.JobId)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>

HRWebApp/HRWebAppUI/Views/Admin/Jobs.cshtml
@model List<HRWebApp.Models.Job>

@{
    ViewBag.Title = "Jobs";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Jobs:</h3>
    </div>
</div>
<div class="row">
    <div class ="col-xs-12">
        <table class="table">
            @foreach (var job in Model)
            {
                <tr>
                    <td>
                        <ul class="jobList">
                            <li>
                                <p>
                                    <b>Job Title : @job.JobTitle</b>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <b>Job Description</b>
                                </p>
                                @job.JobDescription
                            </li>
                            <li>
                                <p>
                                    <b>Job Requirements</b>
                                </p>
                                @job.JobRequirement
                            </li>
                        </ul>
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "EditJob", "Admin", new {id = job.JobId} , new {@class = "btn btn-info", id = "editButton"})
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "DeleteJob", "Admin", new {id = job.JobId}, new {@class = "btn btn-info", id = "deleteButton"})
                    </td>
                </tr>
            }
        </table>
        @Html.ActionLink("Add Job","AddJob","Admin",null,new {@class = "btn btn-success", id = "addButton"})
    </div>
</div>

HRWebApp/HRWebAppUI/Views/Admin/SingleApplication.cshtml
@using HRWebApp.Models
@model HRWebApp.Models.Application

@{
    ViewBag.Title = "SingleApplication";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Application ID : @Model.ApplicationId</h3>
        <h3>Job Applied For : @Model.JobApplyingFor.JobTitle</h3>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <table class="table">
            <tbody>
                <tr>
                    <td>Applicant Name</td>
                    <td>:</td>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(m => m.Address) </td>
                    <td>:</td>
                    <td>@Model.Address.Street1<br />@Model.Address.City<br />@Model.Address.State - @Model.Address.Zipcode</td>
                </tr>
                <tr>
                    <td>Contact Information</td>
                    <td>:</td>
                    <td>@Model.PhoneNumber<br />@Model.EmailId</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(m => m.Dob)</td>
                    <td>:</td>
                    <td>@Model.Dob</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(m => m.SkillSet)</td>
                    <td>:</td>
                    <td>@Model.SkillSet</td>
                </tr>
                <tr>
                    <td>Work History</td>
                    <td>:</td>
                    <td>
                        <ul style="padding-left: 0">
                            @foreach (var item in Model.WorkHistory)
                            {

                                <li>
                                    <p>Job Title : @item.JobTitle</p>
                                    <p>Company Name : @item.CompanyName</p>
                                    <p>Years Worked Here : @item.Years</p>
                                </li>
                            }
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Educational Background</td>
                    <td>:</td>
                    <td>
                        <ul style="padding-left: 0">
                            @foreach (var item in Model.Education)
                            {
                                <li>
                                    <p>Degree : @item.Degree</p>
                                    <p>Graduation Year : @item.GraduationYear</p>
                                    <p>Major : @item.Major</p>
                                    <p>School : @item.School</p>
                                </li>
                            }
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Brief Description</td>
                    <td>:</td>
                    <td>@Model.BriefDescription</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

HRWebApp/HRWebAppUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron mastHead" style="height: 508px">
    <div>
        <img src="/Images/SWG-Shield-Logo.png" class="img-responsive" id="leftImage" />
    </div>
    <div id="rightText" class="panel-body">
        <h1>
            <div id="greyText">SG</div>
            <div id="redText">Corp</div>
        </h1>
        <p>
            <center>
                
                    <button type="submit" style="background-color: transparent; font-family: Dosis; font-weight: 900; font-size: 2em; border: none; color: #B31B27" id="learnMore">Learn More</button>
              
            </center>
        </p>
    </div>
    @*<center>
        <div style="width: 19.3%" id="learnMore">
            <button type="submit" style="background-color: transparent; font-family: Dosis; font-weight: 900; font-size: 2em; border: none; color: #B31B27">Learn More</button>
        </div>
    </center>*@
</div>
<div class="row description col-xs-12">
    <h1 style="padding: 2%; text-align: center">Our Services</h1>
    <ul class="icon-list icons">
        <li>
            <i class="fa fa-magic "></i>
            <p class="listElement">Software Design and Development</p>
        </li>
        <li>
            <i class="fa fa-cloud-upload"></i>
            <p class="listElement">Mobile Development Android And IOS
            </p>
        </li>
        <li>
            <i class="fa fa-connectdevelop"></i>
            <p class="listElement">Web Development</p>
        </li>
        <li>
            <i class="fa fa-tachometer"></i>
            <p class="listElement">Software Testing</p>
        </li>
        <li>
            <i class="fa fa-check"></i>
            <p class="listElement">Application Support/Maintenance</p>
        </li>
        <li>
            <i class="fa fa-wrench"></i>
            <p class="listElement">System Integration</p>
        </li>
    </ul>
    <hr />
    <h1 style="text-align: center">Contact Us Now</h1>
    <center>
        <ul class="socialIcons">
            <li class="twitter"><i class="fa fa-twitter"></i></li>
            <li class="facebook"><i class="fa fa-facebook"></i></li>
            <li class="instagram"><i class="fa fa-instagram"></i></li>
        </ul>
    </center>
</div>

HRWebApp/HRWebAppUI/Views/Job/Jobs.cshtml
@using System.Web.Mvc.Html
@model List<HRWebApp.Models.Job>

@{
    ViewBag.Title = "Jobs";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Current Job Openings:</h3>
    </div>
</div>
<div class="row">
    <div class="col-sm-9">
        <table class="table">
            @foreach (var job in Model)
            {
                
                                
                <tr>
                    <td>
                        <ul class="jobList">
                            <li>
                                <p><b>Job Title : @job.JobTitle</b>
                                </p>
                            </li>
                            <li>
                                <p><b>Job Description</b>
                                </p>
                                @job.JobDescription
                            </li>
                            <li>
                                <p><b>Job Requirements</b>
                                </p>
                                @job.JobRequirement
                            </li>
                        </ul>
                    </td>
                    <td>
                        @Html.ActionLink("Apply Now", "AddApplication", "Job", new {id = job.JobId}, new {@class = "btn btn-info", id = "applyButton"})
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

HRWebApp/HRWebAppUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,500' rel='stylesheet' type='text/css'>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:500,300,400" rel="stylesheet" type="text/css">
    <title>@ViewBag.Title - SG Corp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="container">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SG Corp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="rightIcons">@Html.ActionLink("Careers", "Jobs", "Job")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Jobs", "Jobs", "Admin")</li>
                            <li>@Html.ActionLink("Applications", "Applications", "Admin")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SGCorp Application</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>